/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as CampaignsCampaignIdTasksIndexRouteImport } from './routes/campaigns/$campaignId/tasks/index'
import { Route as CampaignsCampaignIdTasksNewRouteImport } from './routes/campaigns/$campaignId/tasks/new'
import { Route as CampaignsCampaignIdTasksTaskIdEditRouteImport } from './routes/campaigns/$campaignId/tasks/$taskId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdTasksIndexRoute =
  CampaignsCampaignIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdTasksNewRoute =
  CampaignsCampaignIdTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdTasksTaskIdEditRoute =
  CampaignsCampaignIdTasksTaskIdEditRouteImport.update({
    id: '/tasks/$taskId/edit',
    path: '/tasks/$taskId/edit',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns': typeof CampaignsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/campaigns/$campaignId/tasks/new': typeof CampaignsCampaignIdTasksNewRoute
  '/campaigns/$campaignId/tasks': typeof CampaignsCampaignIdTasksIndexRoute
  '/campaigns/$campaignId/tasks/$taskId/edit': typeof CampaignsCampaignIdTasksTaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns': typeof CampaignsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/campaigns/$campaignId/tasks/new': typeof CampaignsCampaignIdTasksNewRoute
  '/campaigns/$campaignId/tasks': typeof CampaignsCampaignIdTasksIndexRoute
  '/campaigns/$campaignId/tasks/$taskId/edit': typeof CampaignsCampaignIdTasksTaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof CampaignsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/campaigns/$campaignId/tasks/new': typeof CampaignsCampaignIdTasksNewRoute
  '/campaigns/$campaignId/tasks/': typeof CampaignsCampaignIdTasksIndexRoute
  '/campaigns/$campaignId/tasks/$taskId/edit': typeof CampaignsCampaignIdTasksTaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns'
    | '/tasks'
    | '/campaigns/$campaignId/tasks/new'
    | '/campaigns/$campaignId/tasks'
    | '/campaigns/$campaignId/tasks/$taskId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns'
    | '/tasks'
    | '/campaigns/$campaignId/tasks/new'
    | '/campaigns/$campaignId/tasks'
    | '/campaigns/$campaignId/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/tasks/'
    | '/campaigns/$campaignId/tasks/new'
    | '/campaigns/$campaignId/tasks/'
    | '/campaigns/$campaignId/tasks/$taskId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/tasks/': {
      id: '/campaigns/$campaignId/tasks/'
      path: '/tasks'
      fullPath: '/campaigns/$campaignId/tasks'
      preLoaderRoute: typeof CampaignsCampaignIdTasksIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/tasks/new': {
      id: '/campaigns/$campaignId/tasks/new'
      path: '/tasks/new'
      fullPath: '/campaigns/$campaignId/tasks/new'
      preLoaderRoute: typeof CampaignsCampaignIdTasksNewRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/tasks/$taskId/edit': {
      id: '/campaigns/$campaignId/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/campaigns/$campaignId/tasks/$taskId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdTasksTaskIdEditRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdTasksNewRoute: typeof CampaignsCampaignIdTasksNewRoute
  CampaignsCampaignIdTasksIndexRoute: typeof CampaignsCampaignIdTasksIndexRoute
  CampaignsCampaignIdTasksTaskIdEditRoute: typeof CampaignsCampaignIdTasksTaskIdEditRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdTasksNewRoute: CampaignsCampaignIdTasksNewRoute,
  CampaignsCampaignIdTasksIndexRoute: CampaignsCampaignIdTasksIndexRoute,
  CampaignsCampaignIdTasksTaskIdEditRoute:
    CampaignsCampaignIdTasksTaskIdEditRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsIndexRoute: CampaignsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
